[project]
name = "ChainNest"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.community-manager]
path = "contracts/community-manager.clar"
depends_on = []

[contracts.content-manager]
path = "contracts/content-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
